//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// HACK: This code was modified by hand.

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("XSpect.MetaTweet.Objects", "AccountActivity", "Account", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(XSpect.MetaTweet.Objects.Account), "Activity", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XSpect.MetaTweet.Objects.Activity))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("XSpect.MetaTweet.Objects", "AccountAnnotation", "Account", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(XSpect.MetaTweet.Objects.Account), "Annotation", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XSpect.MetaTweet.Objects.Annotation))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("XSpect.MetaTweet.Objects", "AccountRelation", "Account", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(XSpect.MetaTweet.Objects.Account), "Relation", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XSpect.MetaTweet.Objects.Relation))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("XSpect.MetaTweet.Objects", "RelationAccount", "Relation", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XSpect.MetaTweet.Objects.Relation), "Account", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(XSpect.MetaTweet.Objects.Account))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("XSpect.MetaTweet.Objects", "AccountMark", "Account", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(XSpect.MetaTweet.Objects.Account), "Mark", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XSpect.MetaTweet.Objects.Mark))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("XSpect.MetaTweet.Objects", "ActivityMark", "Activity", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(XSpect.MetaTweet.Objects.Activity), "Mark", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XSpect.MetaTweet.Objects.Mark))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("XSpect.MetaTweet.Objects", "ActivityReference", "Activity", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(XSpect.MetaTweet.Objects.Activity), "Reference", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XSpect.MetaTweet.Objects.Reference))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("XSpect.MetaTweet.Objects", "ReferenceActivity", "Reference", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XSpect.MetaTweet.Objects.Reference), "Activity", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(XSpect.MetaTweet.Objects.Activity))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("XSpect.MetaTweet.Objects", "ActivityTag", "Activity", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(XSpect.MetaTweet.Objects.Activity), "Tag", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XSpect.MetaTweet.Objects.Tag))]

// Original file name:
// Generation date: 2009/10/05 02:43:30
namespace XSpect.MetaTweet.Objects
{
    
    /// <summary>
    /// There are no comments for StorageEntities in the schema.
    /// </summary>
    public partial class StorageEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new StorageEntities object using the connection string found in the 'StorageEntities' section of the application configuration file.
        /// </summary>
        public StorageEntities() : 
                base("name=StorageEntities", "StorageEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new StorageEntities object.
        /// </summary>
        public StorageEntities(string connectionString) : 
                base(connectionString, "StorageEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new StorageEntities object.
        /// </summary>
        public StorageEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "StorageEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for AccountSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Account> AccountSet
        {
            get
            {
                if ((this._AccountSet == null))
                {
                    this._AccountSet = base.CreateQuery<Account>("[AccountSet]");
                }
                return this._AccountSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Account> _AccountSet;
        /// <summary>
        /// There are no comments for ActivitySet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Activity> ActivitySet
        {
            get
            {
                if ((this._ActivitySet == null))
                {
                    this._ActivitySet = base.CreateQuery<Activity>("[ActivitySet]");
                }
                return this._ActivitySet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Activity> _ActivitySet;
        /// <summary>
        /// There are no comments for AnnotationSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Annotation> AnnotationSet
        {
            get
            {
                if ((this._AnnotationSet == null))
                {
                    this._AnnotationSet = base.CreateQuery<Annotation>("[AnnotationSet]");
                }
                return this._AnnotationSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Annotation> _AnnotationSet;
        /// <summary>
        /// There are no comments for MarkSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Mark> MarkSet
        {
            get
            {
                if ((this._MarkSet == null))
                {
                    this._MarkSet = base.CreateQuery<Mark>("[MarkSet]");
                }
                return this._MarkSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Mark> _MarkSet;
        /// <summary>
        /// There are no comments for ReferenceSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Reference> ReferenceSet
        {
            get
            {
                if ((this._ReferenceSet == null))
                {
                    this._ReferenceSet = base.CreateQuery<Reference>("[ReferenceSet]");
                }
                return this._ReferenceSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Reference> _ReferenceSet;
        /// <summary>
        /// There are no comments for RelationSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Relation> RelationSet
        {
            get
            {
                if ((this._RelationSet == null))
                {
                    this._RelationSet = base.CreateQuery<Relation>("[RelationSet]");
                }
                return this._RelationSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Relation> _RelationSet;
        /// <summary>
        /// There are no comments for TagSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Tag> TagSet
        {
            get
            {
                if ((this._TagSet == null))
                {
                    this._TagSet = base.CreateQuery<Tag>("[TagSet]");
                }
                return this._TagSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Tag> _TagSet;
        /// <summary>
        /// There are no comments for AccountSet in the schema.
        /// </summary>
        public void AddToAccountSet(Account account)
        {
            base.AddObject("AccountSet", account);
        }
        /// <summary>
        /// There are no comments for ActivitySet in the schema.
        /// </summary>
        public void AddToActivitySet(Activity activity)
        {
            base.AddObject("ActivitySet", activity);
        }
        /// <summary>
        /// There are no comments for AnnotationSet in the schema.
        /// </summary>
        public void AddToAnnotationSet(Annotation annotation)
        {
            base.AddObject("AnnotationSet", annotation);
        }
        /// <summary>
        /// There are no comments for MarkSet in the schema.
        /// </summary>
        public void AddToMarkSet(Mark mark)
        {
            base.AddObject("MarkSet", mark);
        }
        /// <summary>
        /// There are no comments for ReferenceSet in the schema.
        /// </summary>
        public void AddToReferenceSet(Reference reference)
        {
            base.AddObject("ReferenceSet", reference);
        }
        /// <summary>
        /// There are no comments for RelationSet in the schema.
        /// </summary>
        public void AddToRelationSet(Relation relation)
        {
            base.AddObject("RelationSet", relation);
        }
        /// <summary>
        /// There are no comments for TagSet in the schema.
        /// </summary>
        public void AddToTagSet(Tag tag)
        {
            base.AddObject("TagSet", tag);
        }
    }
    /// <summary>
    /// 任意のサービスに登録しているユーザを表します。
    /// </summary>
    /// <LongDescription>
    /// アカウントは MetaTweet のデータ構造の頂点に位置する構造で、任意のサービスを利用するユーザを表現します。
    /// </LongDescription>
    /// <KeyProperties>
    /// AccountId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="XSpect.MetaTweet.Objects", Name="Account")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Account : StorageObject
    {
        /// <summary>
        /// Create a new Account object.
        /// </summary>
        /// <param name="accountId">Initial value of AccountId.</param>
        /// <param name="realm">Initial value of Realm.</param>
        public static Account CreateAccount(Storage storage, global::System.Guid accountId, string realm)
        {
            Account account = new Account(storage);
            account.AccountId = accountId;
            account.Realm = realm;
            return account;
        }
        /// <summary>
        /// このアカウントを一意に識別するグローバル一意識別子 (GUID) 値を取得または設定します。
        /// </summary>
        /// <LongDescription>
        /// アカウントはグローバル一意識別子 (GUID) 値によって一意に識別されます。この値は &lt;see cref=&quot;Realm&quot;/&gt; の値に関係なく、全体で一意である必要があります。
        /// </LongDescription>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid AccountId
        {
            get
            {
                return this._AccountId;
            }
            set
            {
                this.OnAccountIdChanging(value);
                this.ReportPropertyChanging("AccountId");
                this._AccountId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AccountId");
                this.OnAccountIdChanged();
            }
        }
        private global::System.Guid _AccountId;
        partial void OnAccountIdChanging(global::System.Guid value);
        partial void OnAccountIdChanged();
        /// <summary>
        /// このアカウントに関連付けられているサービスを表す文字列を取得または設定します。
        /// </summary>
        /// <LongDescription>
        /// Realm はアカウントに関連付けられているサービスを識別する要素です。Realm は自由に指定することができます。通常、Realm はサービスの完全修飾ドメイン名 (FQDN) を逆順に並べた文字列を先頭に配置し、その後に補足的な要素を連結した文字列を指定します (Java のパッケージ命名規約と同じ)。例えば、サービス example.com に関連付けられているアカウントの Realm は &lt;c&gt;com.example&lt;/c&gt; が一般に用いられるべきです。
        /// </LongDescription>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Realm
        {
            get
            {
                return this._Realm;
            }
            set
            {
                this.OnRealmChanging(value);
                this.ReportPropertyChanging("Realm");
                this._Realm = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Realm");
                this.OnRealmChanged();
            }
        }
        private string _Realm;
        partial void OnRealmChanging(string value);
        partial void OnRealmChanged();
        /// <summary>
        /// このアカウントによって行われたアクティビティのシーケンスを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("XSpect.MetaTweet.Objects", "AccountActivity", "Activity")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Activity> Activities
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Activity>("XSpect.MetaTweet.Objects.AccountActivity", "Activity");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Activity>("XSpect.MetaTweet.Objects.AccountActivity", "Activity", value);
                }
            }
        }
        /// <summary>
        /// このアカウントに関連付けられたアノテーションのシーケンスを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("XSpect.MetaTweet.Objects", "AccountAnnotation", "Annotation")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Annotation> Annotations
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Annotation>("XSpect.MetaTweet.Objects.AccountAnnotation", "Annotation");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Annotation>("XSpect.MetaTweet.Objects.AccountAnnotation", "Annotation", value);
                }
            }
        }
        /// <summary>
        /// このアカウントに関連付けられたリレーションのシーケンスを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("XSpect.MetaTweet.Objects", "AccountRelation", "Relation")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Relation> Relations
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Relation>("XSpect.MetaTweet.Objects.AccountRelation", "Relation");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Relation>("XSpect.MetaTweet.Objects.AccountRelation", "Relation", value);
                }
            }
        }
        /// <summary>
        /// このアカウントが対象として関連付けられたリレーションのシーケンスを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("XSpect.MetaTweet.Objects", "RelationAccount", "Relation")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Relation> ReverseRelations
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Relation>("XSpect.MetaTweet.Objects.RelationAccount", "Relation");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Relation>("XSpect.MetaTweet.Objects.RelationAccount", "Relation", value);
                }
            }
        }
        /// <summary>
        /// このアカウントに関連付けられたマークのシーケンスを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("XSpect.MetaTweet.Objects", "AccountMark", "Mark")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Mark> Marks
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Mark>("XSpect.MetaTweet.Objects.AccountMark", "Mark");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Mark>("XSpect.MetaTweet.Objects.AccountMark", "Mark", value);
                }
            }
        }
    }
    /// <summary>
    /// アカウントによって行われた行動を表します。
    /// </summary>
    /// <LongDescription>
    /// アクティビティは、任意のアカウントによって行われたあらゆる行動 (設定値および状態の変更、ポストの投稿を含みます) を表現します。
    /// </LongDescription>
    /// <KeyProperties>
    /// AccountId
    /// Timestamp
    /// Category
    /// SubId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="XSpect.MetaTweet.Objects", Name="Activity")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Activity : StorageObject
    {
        /// <summary>
        /// Create a new Activity object.
        /// </summary>
        /// <param name="accountId">Initial value of AccountId.</param>
        /// <param name="timestamp">Initial value of Timestamp.</param>
        /// <param name="category">Initial value of Category.</param>
        /// <param name="subId">Initial value of SubId.</param>
        public static Activity CreateActivity(Storage storage, global::System.Guid accountId, global::System.DateTime timestamp, string category, string subId)
        {
            Activity activity = new Activity(storage);
            activity.AccountId = accountId;
            activity.Timestamp = timestamp;
            activity.Category = category;
            activity.SubId = subId;
            return activity;
        }
        /// <summary>
        /// このアクティビティを行ったアカウントの ID を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid AccountId
        {
            get
            {
                return this._AccountId;
            }
            set
            {
                this.OnAccountIdChanging(value);
                this.ReportPropertyChanging("AccountId");
                this._AccountId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AccountId");
                this.OnAccountIdChanged();
            }
        }
        private global::System.Guid _AccountId;
        partial void OnAccountIdChanging(global::System.Guid value);
        partial void OnAccountIdChanged();
        /// <summary>
        /// このアクティビティが行われた時刻を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Timestamp
        {
            get
            {
                return this._Timestamp;
            }
            set
            {
                this.OnTimestampChanging(value);
                this.ReportPropertyChanging("Timestamp");
                this._Timestamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Timestamp");
                this.OnTimestampChanged();
            }
        }
        private global::System.DateTime _Timestamp;
        partial void OnTimestampChanging(global::System.DateTime value);
        partial void OnTimestampChanged();
        /// <summary>
        /// このアクティビティが表す行動の種類を表す文字列を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                this.ReportPropertyChanging("Category");
                this._Category = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Category");
                this.OnCategoryChanged();
            }
        }
        private string _Category;
        partial void OnCategoryChanging(string value);
        partial void OnCategoryChanged();
        /// <summary>
        /// このアクティビティを、同一アカウント・時刻・カテゴリの他のアクティビティと識別するための文字列、または、このアクティビティを一意に識別する文字列を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SubId
        {
            get
            {
                return this._SubId;
            }
            set
            {
                this.OnSubIdChanging(value);
                this.ReportPropertyChanging("SubId");
                this._SubId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SubId");
                this.OnSubIdChanged();
            }
        }
        private string _SubId;
        partial void OnSubIdChanging(string value);
        partial void OnSubIdChanged();
        /// <summary>
        /// このアクティビティを行ったユーザ エージェントを識別する文字列を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAgent
        {
            get
            {
                return this._UserAgent;
            }
            set
            {
                this.OnUserAgentChanging(value);
                this.ReportPropertyChanging("UserAgent");
                this._UserAgent = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UserAgent");
                this.OnUserAgentChanged();
            }
        }
        private string _UserAgent;
        partial void OnUserAgentChanging(string value);
        partial void OnUserAgentChanged();
        /// <summary>
        /// このアクティビティの値となる文字列を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this.ReportPropertyChanging("Value");
                this._Value = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Value");
                this.OnValueChanged();
            }
        }
        private string _Value;
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        /// <summary>
        /// このアクティビティの値となるバイト列を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._Data);
            }
            set
            {
                this.OnDataChanging(value);
                this.ReportPropertyChanging("Data");
                this._Data = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Data");
                this.OnDataChanged();
            }
        }
        private byte[] _Data;
        partial void OnDataChanging(byte[] value);
        partial void OnDataChanged();
        /// <summary>
        /// このアクティビティを行ったアカウントを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("XSpect.MetaTweet.Objects", "AccountActivity", "Account")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Account Account
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("XSpect.MetaTweet.Objects.AccountActivity", "Account").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("XSpect.MetaTweet.Objects.AccountActivity", "Account").Value = value;
            }
        }
        /// <summary>
        /// このアクティビティを行ったアカウントを取得または設定します。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Account> AccountReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("XSpect.MetaTweet.Objects.AccountActivity", "Account");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Account>("XSpect.MetaTweet.Objects.AccountActivity", "Account", value);
                }
            }
        }
        /// <summary>
        /// このアクティビティに関連付けられたマークのシーケンスを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("XSpect.MetaTweet.Objects", "ActivityMark", "Mark")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Mark> Marks
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Mark>("XSpect.MetaTweet.Objects.ActivityMark", "Mark");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Mark>("XSpect.MetaTweet.Objects.ActivityMark", "Mark", value);
                }
            }
        }
        /// <summary>
        /// このアクティビティに関連付けられたリファレンスのシーケンスを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("XSpect.MetaTweet.Objects", "ActivityReference", "Reference")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Reference> References
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Reference>("XSpect.MetaTweet.Objects.ActivityReference", "Reference");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Reference>("XSpect.MetaTweet.Objects.ActivityReference", "Reference", value);
                }
            }
        }
        /// <summary>
        /// このアクティビティが対象として関連付けられたリファレンスのシーケンスを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("XSpect.MetaTweet.Objects", "ReferenceActivity", "Reference")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Reference> ReverseReferences
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Reference>("XSpect.MetaTweet.Objects.ReferenceActivity", "Reference");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Reference>("XSpect.MetaTweet.Objects.ReferenceActivity", "Reference", value);
                }
            }
        }
        /// <summary>
        /// このアクティビティに関連付けられたタグのシーケンスを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("XSpect.MetaTweet.Objects", "ActivityTag", "Tag")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Tag> Tags
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Tag>("XSpect.MetaTweet.Objects.ActivityTag", "Tag");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Tag>("XSpect.MetaTweet.Objects.ActivityTag", "Tag", value);
                }
            }
        }
    }
    /// <summary>
    /// アカウントに追加して記述される情報を表します。
    /// </summary>
    /// <LongDescription>
    /// アノテーションは、アカウントに追加の情報を記述する付与情報です。
    /// </LongDescription>
    /// <KeyProperties>
    /// AccountId
    /// Name
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="XSpect.MetaTweet.Objects", Name="Annotation")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Annotation : StorageObject
    {
        /// <summary>
        /// Create a new Annotation object.
        /// </summary>
        /// <param name="accountId">Initial value of AccountId.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Annotation CreateAnnotation(Storage storage, global::System.Guid accountId, string name)
        {
            Annotation annotation = new Annotation(storage);
            annotation.AccountId = accountId;
            annotation.Name = name;
            return annotation;
        }
        /// <summary>
        /// このアノテーションが関連付けられているアカウントの ID を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid AccountId
        {
            get
            {
                return this._AccountId;
            }
            set
            {
                this.OnAccountIdChanging(value);
                this.ReportPropertyChanging("AccountId");
                this._AccountId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AccountId");
                this.OnAccountIdChanged();
            }
        }
        private global::System.Guid _AccountId;
        partial void OnAccountIdChanging(global::System.Guid value);
        partial void OnAccountIdChanged();
        /// <summary>
        /// このアノテーションの意味となる文字列を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// このアノテーションが関連付けられているアカウントを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("XSpect.MetaTweet.Objects", "AccountAnnotation", "Account")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Account Account
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("XSpect.MetaTweet.Objects.AccountAnnotation", "Account").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("XSpect.MetaTweet.Objects.AccountAnnotation", "Account").Value = value;
            }
        }
        /// <summary>
        /// このアノテーションが関連付けられているアカウントを取得または設定します。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Account> AccountReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("XSpect.MetaTweet.Objects.AccountAnnotation", "Account");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Account>("XSpect.MetaTweet.Objects.AccountAnnotation", "Account", value);
                }
            }
        }
    }
    /// <summary>
    /// アカウントとアクティビティの関係を記述する情報を表します。
    /// </summary>
    /// <LongDescription>
    /// マークは、アカウントとアクティビティの関係を記述する付与情報です。
    /// </LongDescription>
    /// <KeyProperties>
    /// AccountId
    /// Name
    /// MarkingAccountId
    /// MarkingTimestamp
    /// MarkingCategory
    /// MarkingSubId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="XSpect.MetaTweet.Objects", Name="Mark")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Mark : StorageObject
    {
        /// <summary>
        /// Create a new Mark object.
        /// </summary>
        /// <param name="accountId">Initial value of AccountId.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="markingAccountId">Initial value of MarkingAccountId.</param>
        /// <param name="markingTimestamp">Initial value of MarkingTimestamp.</param>
        /// <param name="markingCategory">Initial value of MarkingCategory.</param>
        /// <param name="markingSubId">Initial value of MarkingSubId.</param>
        public static Mark CreateMark(Storage storage, global::System.Guid accountId, string name, global::System.Guid markingAccountId, global::System.DateTime markingTimestamp, string markingCategory, string markingSubId)
        {
            Mark mark = new Mark(storage);
            mark.AccountId = accountId;
            mark.Name = name;
            mark.MarkingAccountId = markingAccountId;
            mark.MarkingTimestamp = markingTimestamp;
            mark.MarkingCategory = markingCategory;
            mark.MarkingSubId = markingSubId;
            return mark;
        }
        /// <summary>
        /// このマークが関連付けられているアカウントの ID を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid AccountId
        {
            get
            {
                return this._AccountId;
            }
            set
            {
                this.OnAccountIdChanging(value);
                this.ReportPropertyChanging("AccountId");
                this._AccountId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AccountId");
                this.OnAccountIdChanged();
            }
        }
        private global::System.Guid _AccountId;
        partial void OnAccountIdChanging(global::System.Guid value);
        partial void OnAccountIdChanged();
        /// <summary>
        /// このマークの意味となる文字列を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// このマークが関連付けられる先のアクティビティのアカウント ID を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid MarkingAccountId
        {
            get
            {
                return this._MarkingAccountId;
            }
            set
            {
                this.OnMarkingAccountIdChanging(value);
                this.ReportPropertyChanging("MarkingAccountId");
                this._MarkingAccountId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MarkingAccountId");
                this.OnMarkingAccountIdChanged();
            }
        }
        private global::System.Guid _MarkingAccountId;
        partial void OnMarkingAccountIdChanging(global::System.Guid value);
        partial void OnMarkingAccountIdChanged();
        /// <summary>
        /// このマークが関連付けられる先のアクティビティのタイムスタンプを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime MarkingTimestamp
        {
            get
            {
                return this._MarkingTimestamp;
            }
            set
            {
                this.OnMarkingTimestampChanging(value);
                this.ReportPropertyChanging("MarkingTimestamp");
                this._MarkingTimestamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MarkingTimestamp");
                this.OnMarkingTimestampChanged();
            }
        }
        private global::System.DateTime _MarkingTimestamp;
        partial void OnMarkingTimestampChanging(global::System.DateTime value);
        partial void OnMarkingTimestampChanged();
        /// <summary>
        /// このマークが関連付けられる先のアクティビティのカテゴリを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string MarkingCategory
        {
            get
            {
                return this._MarkingCategory;
            }
            set
            {
                this.OnMarkingCategoryChanging(value);
                this.ReportPropertyChanging("MarkingCategory");
                this._MarkingCategory = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("MarkingCategory");
                this.OnMarkingCategoryChanged();
            }
        }
        private string _MarkingCategory;
        partial void OnMarkingCategoryChanging(string value);
        partial void OnMarkingCategoryChanged();
        /// <summary>
        /// このマークが関連付けられる先のアクティビティのサブ ID を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string MarkingSubId
        {
            get
            {
                return this._MarkingSubId;
            }
            set
            {
                this.OnMarkingSubIdChanging(value);
                this.ReportPropertyChanging("MarkingSubId");
                this._MarkingSubId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("MarkingSubId");
                this.OnMarkingSubIdChanged();
            }
        }
        private string _MarkingSubId;
        partial void OnMarkingSubIdChanging(string value);
        partial void OnMarkingSubIdChanged();
        /// <summary>
        /// このマークが関連付けられているアカウントを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("XSpect.MetaTweet.Objects", "AccountMark", "Account")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Account Account
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("XSpect.MetaTweet.Objects.AccountMark", "Account").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("XSpect.MetaTweet.Objects.AccountMark", "Account").Value = value;
            }
        }
        /// <summary>
        /// このマークが関連付けられているアカウントを取得または設定します。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Account> AccountReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("XSpect.MetaTweet.Objects.AccountMark", "Account");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Account>("XSpect.MetaTweet.Objects.AccountMark", "Account", value);
                }
            }
        }
        /// <summary>
        /// このマークが関連付けられる先のアクティビティを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("XSpect.MetaTweet.Objects", "ActivityMark", "Activity")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Activity MarkingActivity
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Activity>("XSpect.MetaTweet.Objects.ActivityMark", "Activity").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Activity>("XSpect.MetaTweet.Objects.ActivityMark", "Activity").Value = value;
            }
        }
        /// <summary>
        /// このマークが関連付けられる先のアクティビティを取得または設定します。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Activity> MarkingActivityReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Activity>("XSpect.MetaTweet.Objects.ActivityMark", "Activity");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Activity>("XSpect.MetaTweet.Objects.ActivityMark", "Activity", value);
                }
            }
        }
    }
    /// <summary>
    /// アクティビティ同士の関係を記述する情報を表します。
    /// </summary>
    /// <LongDescription>
    /// リファレンスは、アクティビティ同士の関係を記述する付与情報です。
    /// </LongDescription>
    /// <KeyProperties>
    /// AccountId
    /// Timestamp
    /// Category
    /// SubId
    /// Name
    /// ReferringAccountId
    /// ReferringTimestamp
    /// ReferringCategory
    /// ReferringSubId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="XSpect.MetaTweet.Objects", Name="Reference")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Reference : StorageObject
    {
        /// <summary>
        /// Create a new Reference object.
        /// </summary>
        /// <param name="accountId">Initial value of AccountId.</param>
        /// <param name="timestamp">Initial value of Timestamp.</param>
        /// <param name="category">Initial value of Category.</param>
        /// <param name="subId">Initial value of SubId.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="referringAccountId">Initial value of ReferringAccountId.</param>
        /// <param name="referringTimestamp">Initial value of ReferringTimestamp.</param>
        /// <param name="referringCategory">Initial value of ReferringCategory.</param>
        /// <param name="referringSubId">Initial value of ReferringSubId.</param>
        public static Reference CreateReference(Storage storage, global::System.Guid accountId, global::System.DateTime timestamp, string category, string subId, string name, global::System.Guid referringAccountId, global::System.DateTime referringTimestamp, string referringCategory, string referringSubId)
        {
            Reference reference = new Reference(storage);
            reference.AccountId = accountId;
            reference.Timestamp = timestamp;
            reference.Category = category;
            reference.SubId = subId;
            reference.Name = name;
            reference.ReferringAccountId = referringAccountId;
            reference.ReferringTimestamp = referringTimestamp;
            reference.ReferringCategory = referringCategory;
            reference.ReferringSubId = referringSubId;
            return reference;
        }
        /// <summary>
        /// このリファレンスが関連付けられているアクティビティのアカウント ID を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid AccountId
        {
            get
            {
                return this._AccountId;
            }
            set
            {
                this.OnAccountIdChanging(value);
                this.ReportPropertyChanging("AccountId");
                this._AccountId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AccountId");
                this.OnAccountIdChanged();
            }
        }
        private global::System.Guid _AccountId;
        partial void OnAccountIdChanging(global::System.Guid value);
        partial void OnAccountIdChanged();
        /// <summary>
        /// このリファレンスが関連付けられているアクティビティのタイムスタンプを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Timestamp
        {
            get
            {
                return this._Timestamp;
            }
            set
            {
                this.OnTimestampChanging(value);
                this.ReportPropertyChanging("Timestamp");
                this._Timestamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Timestamp");
                this.OnTimestampChanged();
            }
        }
        private global::System.DateTime _Timestamp;
        partial void OnTimestampChanging(global::System.DateTime value);
        partial void OnTimestampChanged();
        /// <summary>
        /// このリファレンスが関連付けられているアクティビティのカテゴリを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                this.ReportPropertyChanging("Category");
                this._Category = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Category");
                this.OnCategoryChanged();
            }
        }
        private string _Category;
        partial void OnCategoryChanging(string value);
        partial void OnCategoryChanged();
        /// <summary>
        /// このリファレンスが関連付けられているアクティビティのサブ ID を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SubId
        {
            get
            {
                return this._SubId;
            }
            set
            {
                this.OnSubIdChanging(value);
                this.ReportPropertyChanging("SubId");
                this._SubId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SubId");
                this.OnSubIdChanged();
            }
        }
        private string _SubId;
        partial void OnSubIdChanging(string value);
        partial void OnSubIdChanged();
        /// <summary>
        /// このリファレンスの意味となる文字列を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// このリファレンスが関連付けられる先のアクティビティのアカウント ID を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ReferringAccountId
        {
            get
            {
                return this._ReferringAccountId;
            }
            set
            {
                this.OnReferringAccountIdChanging(value);
                this.ReportPropertyChanging("ReferringAccountId");
                this._ReferringAccountId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ReferringAccountId");
                this.OnReferringAccountIdChanged();
            }
        }
        private global::System.Guid _ReferringAccountId;
        partial void OnReferringAccountIdChanging(global::System.Guid value);
        partial void OnReferringAccountIdChanged();
        /// <summary>
        /// このリファレンスが関連付けられる先のアクティビティのタイムスタンプを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ReferringTimestamp
        {
            get
            {
                return this._ReferringTimestamp;
            }
            set
            {
                this.OnReferringTimestampChanging(value);
                this.ReportPropertyChanging("ReferringTimestamp");
                this._ReferringTimestamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ReferringTimestamp");
                this.OnReferringTimestampChanged();
            }
        }
        private global::System.DateTime _ReferringTimestamp;
        partial void OnReferringTimestampChanging(global::System.DateTime value);
        partial void OnReferringTimestampChanged();
        /// <summary>
        /// このリファレンスが関連付けられる先のアクティビティのカテゴリを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferringCategory
        {
            get
            {
                return this._ReferringCategory;
            }
            set
            {
                this.OnReferringCategoryChanging(value);
                this.ReportPropertyChanging("ReferringCategory");
                this._ReferringCategory = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ReferringCategory");
                this.OnReferringCategoryChanged();
            }
        }
        private string _ReferringCategory;
        partial void OnReferringCategoryChanging(string value);
        partial void OnReferringCategoryChanged();
        /// <summary>
        /// このリファレンスが関連付けられる先のアクティビティのサブ ID を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferringSubId
        {
            get
            {
                return this._ReferringSubId;
            }
            set
            {
                this.OnReferringSubIdChanging(value);
                this.ReportPropertyChanging("ReferringSubId");
                this._ReferringSubId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ReferringSubId");
                this.OnReferringSubIdChanged();
            }
        }
        private string _ReferringSubId;
        partial void OnReferringSubIdChanging(string value);
        partial void OnReferringSubIdChanged();
        /// <summary>
        /// このリファレンスが関連付けられているアクティビティを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("XSpect.MetaTweet.Objects", "ActivityReference", "Activity")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Activity Activity
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Activity>("XSpect.MetaTweet.Objects.ActivityReference", "Activity").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Activity>("XSpect.MetaTweet.Objects.ActivityReference", "Activity").Value = value;
            }
        }
        /// <summary>
        /// このリファレンスが関連付けられているアクティビティを取得または設定します。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Activity> ActivityReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Activity>("XSpect.MetaTweet.Objects.ActivityReference", "Activity");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Activity>("XSpect.MetaTweet.Objects.ActivityReference", "Activity", value);
                }
            }
        }
        /// <summary>
        /// このリファレンスが関連付けられる先のアクティビティを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("XSpect.MetaTweet.Objects", "ReferenceActivity", "Activity")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Activity ReferringActivity
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Activity>("XSpect.MetaTweet.Objects.ReferenceActivity", "Activity").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Activity>("XSpect.MetaTweet.Objects.ReferenceActivity", "Activity").Value = value;
            }
        }
        /// <summary>
        /// このリファレンスが関連付けられる先のアクティビティを取得または設定します。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Activity> ReferringActivityReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Activity>("XSpect.MetaTweet.Objects.ReferenceActivity", "Activity");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Activity>("XSpect.MetaTweet.Objects.ReferenceActivity", "Activity", value);
                }
            }
        }
    }
    /// <summary>
    /// アカウント同士の関係を記述する情報を表します。
    /// </summary>
    /// <LongDescription>
    /// リレーションは、アカウント同士の関係を記述する付与情報です。
    /// </LongDescription>
    /// <KeyProperties>
    /// AccountId
    /// Name
    /// RelatingAccountId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="XSpect.MetaTweet.Objects", Name="Relation")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Relation : StorageObject
    {
        /// <summary>
        /// Create a new Relation object.
        /// </summary>
        /// <param name="accountId">Initial value of AccountId.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="relatingAccountId">Initial value of RelatingAccountId.</param>
        public static Relation CreateRelation(Storage storage, global::System.Guid accountId, string name, global::System.Guid relatingAccountId)
        {
            Relation relation = new Relation(storage);
            relation.AccountId = accountId;
            relation.Name = name;
            relation.RelatingAccountId = relatingAccountId;
            return relation;
        }
        /// <summary>
        /// このリレーションが関連付けられているアカウントの ID を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid AccountId
        {
            get
            {
                return this._AccountId;
            }
            set
            {
                this.OnAccountIdChanging(value);
                this.ReportPropertyChanging("AccountId");
                this._AccountId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AccountId");
                this.OnAccountIdChanged();
            }
        }
        private global::System.Guid _AccountId;
        partial void OnAccountIdChanging(global::System.Guid value);
        partial void OnAccountIdChanged();
        /// <summary>
        /// このリレーションの意味となる文字列を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// このリレーションが関連付けられる先のアカウントの ID を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid RelatingAccountId
        {
            get
            {
                return this._RelatingAccountId;
            }
            set
            {
                this.OnRelatingAccountIdChanging(value);
                this.ReportPropertyChanging("RelatingAccountId");
                this._RelatingAccountId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("RelatingAccountId");
                this.OnRelatingAccountIdChanged();
            }
        }
        private global::System.Guid _RelatingAccountId;
        partial void OnRelatingAccountIdChanging(global::System.Guid value);
        partial void OnRelatingAccountIdChanged();
        /// <summary>
        /// このリレーションが関連付けられているアカウントを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("XSpect.MetaTweet.Objects", "AccountRelation", "Account")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Account Account
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("XSpect.MetaTweet.Objects.AccountRelation", "Account").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("XSpect.MetaTweet.Objects.AccountRelation", "Account").Value = value;
            }
        }
        /// <summary>
        /// このリレーションが関連付けられているアカウントを取得または設定します。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Account> AccountReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("XSpect.MetaTweet.Objects.AccountRelation", "Account");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Account>("XSpect.MetaTweet.Objects.AccountRelation", "Account", value);
                }
            }
        }
        /// <summary>
        /// このリレーションが関連付けられる先のアカウントを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("XSpect.MetaTweet.Objects", "RelationAccount", "Account")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Account RelatingAccount
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("XSpect.MetaTweet.Objects.RelationAccount", "Account").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("XSpect.MetaTweet.Objects.RelationAccount", "Account").Value = value;
            }
        }
        /// <summary>
        /// このリレーションが関連付けられる先のアカウントを取得または設定します。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Account> RelatingAccountReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("XSpect.MetaTweet.Objects.RelationAccount", "Account");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Account>("XSpect.MetaTweet.Objects.RelationAccount", "Account", value);
                }
            }
        }
    }
    /// <summary>
    /// アクティビティに追加して記述される情報を表します。
    /// </summary>
    /// <LongDescription>
    /// タグは、アクティビティに追加の情報を記述する付与情報です。
    /// </LongDescription>
    /// <KeyProperties>
    /// AccountId
    /// Timestamp
    /// Category
    /// SubId
    /// Name
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="XSpect.MetaTweet.Objects", Name="Tag")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Tag : StorageObject
    {
        /// <summary>
        /// Create a new Tag object.
        /// </summary>
        /// <param name="accountId">Initial value of AccountId.</param>
        /// <param name="timestamp">Initial value of Timestamp.</param>
        /// <param name="category">Initial value of Category.</param>
        /// <param name="subId">Initial value of SubId.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Tag CreateTag(Storage storage, global::System.Guid accountId, global::System.DateTime timestamp, string category, string subId, string name)
        {
            Tag tag = new Tag(storage);
            tag.AccountId = accountId;
            tag.Timestamp = timestamp;
            tag.Category = category;
            tag.SubId = subId;
            tag.Name = name;
            return tag;
        }
        /// <summary>
        /// このタグが関連付けられているアクティビティのアカウント ID を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid AccountId
        {
            get
            {
                return this._AccountId;
            }
            set
            {
                this.OnAccountIdChanging(value);
                this.ReportPropertyChanging("AccountId");
                this._AccountId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AccountId");
                this.OnAccountIdChanged();
            }
        }
        private global::System.Guid _AccountId;
        partial void OnAccountIdChanging(global::System.Guid value);
        partial void OnAccountIdChanged();
        /// <summary>
        /// このタグが関連付けられているアクティビティのタイムスタンプを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Timestamp
        {
            get
            {
                return this._Timestamp;
            }
            set
            {
                this.OnTimestampChanging(value);
                this.ReportPropertyChanging("Timestamp");
                this._Timestamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Timestamp");
                this.OnTimestampChanged();
            }
        }
        private global::System.DateTime _Timestamp;
        partial void OnTimestampChanging(global::System.DateTime value);
        partial void OnTimestampChanged();
        /// <summary>
        /// このタグが関連付けられているアクティビティのカテゴリを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                this.ReportPropertyChanging("Category");
                this._Category = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Category");
                this.OnCategoryChanged();
            }
        }
        private string _Category;
        partial void OnCategoryChanging(string value);
        partial void OnCategoryChanged();
        /// <summary>
        /// このタグが関連付けられているアクティビティのサブ ID を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SubId
        {
            get
            {
                return this._SubId;
            }
            set
            {
                this.OnSubIdChanging(value);
                this.ReportPropertyChanging("SubId");
                this._SubId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SubId");
                this.OnSubIdChanged();
            }
        }
        private string _SubId;
        partial void OnSubIdChanging(string value);
        partial void OnSubIdChanged();
        /// <summary>
        /// このタグの意味となる文字列を取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// このタグが関連付けられているアクティビティを取得または設定します。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("XSpect.MetaTweet.Objects", "ActivityTag", "Activity")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Activity Activity
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Activity>("XSpect.MetaTweet.Objects.ActivityTag", "Activity").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Activity>("XSpect.MetaTweet.Objects.ActivityTag", "Activity").Value = value;
            }
        }
        /// <summary>
        /// このタグが関連付けられているアクティビティを取得または設定します。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Activity> ActivityReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Activity>("XSpect.MetaTweet.Objects.ActivityTag", "Activity");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Activity>("XSpect.MetaTweet.Objects.ActivityTag", "Activity", value);
                }
            }
        }
    }
}
