//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3053
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSpect.MetaTweet.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XSpect.MetaTweet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   MetaTweet Host Service version {0}\nCopyright © 2008 Takeshi KIRIYA, XSpect Project &lt;takeshik@xspect.org&gt; All rights reserved.\n\nThis program comes with ABSOLUTELY NO WARRANTY; for details access to {1}. This is free software, and you are welcome to redistribute it under certain conditions; access {2} for details. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServiceHostInitialized {
            get {
                return ResourceManager.GetString("ServiceHostInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MetaTweet Host Service was resumed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServiceHostOnContinue {
            get {
                return ResourceManager.GetString("ServiceHostOnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MetaTweet Host Service was paused. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServiceHostOnPause {
            get {
                return ResourceManager.GetString("ServiceHostOnPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MetaTweet Host Service was started. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServiceHostOnStart {
            get {
                return ResourceManager.GetString("ServiceHostOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MetaTweet Host Service was stopped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServiceHostOnStop {
            get {
                return ResourceManager.GetString("ServiceHostOnStop", resourceCulture);
            }
        }
    }
}
