###
### UpdateVersionInfo.py
###
### Using: lib/ipy util/UpdateVersionInfo.py <Directory>
###

import clr
import sys
from System import *

Environment.CurrentDirectory = sys.argv[-1]
entries = file(r".svn\entries").readlines()
for i in range(len(entries) - 1):
    entries[i] = entries[i].Trim()

directory = entries[4][:entries[4].LastIndexOf('/')]['http://svn.metatweet.org/svnroot/metatweet/'.Length:]
commitDate = DateTime.Parse(entries[9]).ToUniversalTime().ToString("R");
builtDate = DateTime.Now.ToUniversalTime().ToString("R");
revision = entries[10]
filever = ""
if not directory.Contains("tags"):
    filever = "0.0.0." + revision
elif directory.count(".") == 1:
    filever = directory['tags/'.Length:] + ".0." + revision
elif directory.count(".") == 2:
    filever = directory['tags/'.Length:] + "." + revision

output = """// -*- mode: csharp; encoding: utf-8; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil; -*-
// vim:set ft=cs fenc=utf-8 ts=4 sw=4 sts=4 et:
// This file is generated by util/UpdateVersionInfo.py.

using System;

internal static class ThisAssembly
{
"""

output += "    internal const String BaseDirectory = \"" + directory + "\";\n"
output += "    internal const String CommitedAt = \"" + commitDate + "\";\n"
output += "    internal const String BuiltAt = \"" + builtDate + "\";\n"
output += "    internal const Int32 Revision = " + revision + ";\n"
output += "    internal const String FileVersion = \"" + filever + "\";\n"
output += "}\n"

file = file(r"Properties\ThisAssembly.cs", 'w').write(output)
