#!/usr/bin/python

###
### UpdateVersionInfo.py
###
### Using: lib/ipy util/UpdateVersionInfo.py <Directory> [-clean]
###

import clr
import sys
from System import *
from System.IO import *

verFile = "Properties/ThisAssembly.cs"

Environment.CurrentDirectory = sys.argv[1]
if not Directory.Exists(".svn"):
    sys.exit()
elif sys.argv.Count > 2 and sys.argv[2] == "-clean":
    File.Delete(verFile)
    print "Deleted: " + DirectoryInfo(Environment.CurrentDirectory).Name + "/" + verFile
    sys.exit()

entries = File.ReadAllLines(".svn/entries")

directory = entries[4][:entries[4].LastIndexOf('/')]['http://svn.metatweet.org/svnroot/metatweet/'.Length:]
commitDate = DateTime.Parse(entries[9]).ToUniversalTime().ToString("R");
revision = entries[10]
entireRevision = entries[3]
filever = ""
if not directory.Contains("tags"):
    filever = "0.0.0." + revision
elif directory.count(".") == 1:
    filever = directory['tags/'.Length + 1:] + ".0." + revision
elif directory.count(".") == 2:
    filever = directory['tags/'.Length + 1:] + "." + revision

output = """// -*- mode: csharp; encoding: utf-8; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil; -*-
// vim:set ft=cs fenc=utf-8 ts=4 sw=4 sts=4 et:
// This file is generated by util/UpdateVersionInfo.py.

using System;

internal static class ThisAssembly
{
"""

output += "    internal const String BaseDirectory = \"" + directory + "\";\n"
output += "    internal const String CommitedAt = \"" + commitDate + "\";\n"
output += "    internal const Int32 Revision = " + revision + ";\n"
output += "    internal const Int32 EntireRevision = " + entireRevision + ";\n"
output += "    internal const String FileVersion = \"" + filever + "\";\n"
output += "}\n"

if not (File.Exists(verFile) and File.ReadAllText(verFile) == output):
    File.WriteAllText(verFile, output)
    print "Updated: " + DirectoryInfo(Environment.CurrentDirectory).Name + "/" + verFile
