//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSpect.MetaTweet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XSpect.MetaTweet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow &quot;{0}&quot; finished to perform..
        /// </summary>
        internal static string FlowPerformed {
            get {
                return ResourceManager.GetString("FlowPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow &quot;{0}&quot; started to perform.
        ///  Selector: {1}
        ///  Input: {2}
        ///  Storage: {3}
        ///  Arguments:
        ///{4}
        ///  Output type: {5}.
        /// </summary>
        internal static string FlowPerforming {
            get {
                return ResourceManager.GetString("FlowPerforming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module object &quot;{0}&quot; was configured with file &quot;{1}&quot;..
        /// </summary>
        internal static string ModuleObjectConfigured {
            get {
                return ResourceManager.GetString("ModuleObjectConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module object &quot;{0}&quot; was terminated..
        /// </summary>
        internal static string ModuleObjectDisposed {
            get {
                return ResourceManager.GetString("ModuleObjectDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module object &quot;{0}&quot; is terminating..
        /// </summary>
        internal static string ModuleObjectDisposing {
            get {
                return ResourceManager.GetString("ModuleObjectDisposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module object &quot;{0}&quot; was initialized..
        /// </summary>
        internal static string ModuleObjectInitialized {
            get {
                return ResourceManager.GetString("ModuleObjectInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module object &quot;{0}&quot; is initializing..
        /// </summary>
        internal static string ModuleObjectInitializing {
            get {
                return ResourceManager.GetString("ModuleObjectInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servant &quot;{0}&quot; was aborted..
        /// </summary>
        internal static string ServantAborted {
            get {
                return ResourceManager.GetString("ServantAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servant &quot;{0}&quot; is aborting..
        /// </summary>
        internal static string ServantAborting {
            get {
                return ResourceManager.GetString("ServantAborting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servant &quot;{0}&quot; was started..
        /// </summary>
        internal static string ServantStarted {
            get {
                return ResourceManager.GetString("ServantStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servant &quot;{0}&quot; is starting..
        /// </summary>
        internal static string ServantStarting {
            get {
                return ResourceManager.GetString("ServantStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servant &quot;{0}&quot; was stopped..
        /// </summary>
        internal static string ServantStopped {
            get {
                return ResourceManager.GetString("ServantStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servant &quot;{0}&quot; is stopping..
        /// </summary>
        internal static string ServantStopping {
            get {
                return ResourceManager.GetString("ServantStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; closed session &quot;{1}&quot;..
        /// </summary>
        internal static string StorageClosedSession {
            get {
                return ResourceManager.GetString("StorageClosedSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; session &quot;{1}&quot; created object(s) (
        ///{2}
        ///)..
        /// </summary>
        internal static string StorageCreated {
            get {
                return ResourceManager.GetString("StorageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; session &quot;{1}&quot; deleted object(s) (
        ///{2}
        ///)..
        /// </summary>
        internal static string StorageDeleted {
            get {
                return ResourceManager.GetString("StorageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; session &quot;{1}&quot; loaded object(s) (
        ///{2}
        ///), returned {3} object(s)..
        /// </summary>
        internal static string StorageLoaded {
            get {
                return ResourceManager.GetString("StorageLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; opened new session &quot;{1}&quot;..
        /// </summary>
        internal static string StorageOpenedSession {
            get {
                return ResourceManager.GetString("StorageOpenedSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; session &quot;{1}&quot; queried object(s) (
        ///{2}
        ///), returned {3} object(s)..
        /// </summary>
        internal static string StorageQueried {
            get {
                return ResourceManager.GetString("StorageQueried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; session &quot;{1}&quot; updated..
        /// </summary>
        internal static string StorageUpdated {
            get {
                return ResourceManager.GetString("StorageUpdated", resourceCulture);
            }
        }
    }
}
