//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSpect.MetaTweet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XSpect.MetaTweet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilterFlow &quot;{0}&quot; finished to perform; {1} filtered..
        /// </summary>
        public static string FilterFlowPerformed {
            get {
                return ResourceManager.GetString("FilterFlowPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilterFlow &quot;{0}&quot; started to perform.
        ///  Selector: {1}
        ///  Input: {2}
        ///  Storage: {3}
        ///  Arguments:
        ///{4}.
        /// </summary>
        public static string FilterFlowPerforming {
            get {
                return ResourceManager.GetString("FilterFlowPerforming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputFlow &quot;{0}&quot; finished to perform; {1} inputted..
        /// </summary>
        public static string InputFlowPerformed {
            get {
                return ResourceManager.GetString("InputFlowPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputFlow &quot;{0}&quot; started to perform.
        ///  Selector: {1}
        ///  Storage: {2}
        ///  Arguments:
        ///{3}.
        /// </summary>
        public static string InputFlowPerforming {
            get {
                return ResourceManager.GetString("InputFlowPerforming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module assembly &quot;{0}&quot; was loaded..
        /// </summary>
        public static string ModuleAssemblyLoaded {
            get {
                return ResourceManager.GetString("ModuleAssemblyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module assembly &quot;{0}&quot; was unloaded..
        /// </summary>
        public static string ModuleAssemblyUnloaded {
            get {
                return ResourceManager.GetString("ModuleAssemblyUnloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module object &quot;{1}&quot; ({0}) in {2} was added..
        /// </summary>
        public static string ModuleObjectAdded {
            get {
                return ResourceManager.GetString("ModuleObjectAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module object &quot;{0}&quot; was configured with file &quot;{1}&quot;..
        /// </summary>
        public static string ModuleObjectConfigured {
            get {
                return ResourceManager.GetString("ModuleObjectConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module object &quot;{0}&quot; was terminated..
        /// </summary>
        public static string ModuleObjectDisposed {
            get {
                return ResourceManager.GetString("ModuleObjectDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module object &quot;{0}&quot; is terminating..
        /// </summary>
        public static string ModuleObjectDisposing {
            get {
                return ResourceManager.GetString("ModuleObjectDisposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module object &quot;{0}&quot; was initialized..
        /// </summary>
        public static string ModuleObjectInitialized {
            get {
                return ResourceManager.GetString("ModuleObjectInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module object &quot;{0}&quot; is initializing..
        /// </summary>
        public static string ModuleObjectInitializing {
            get {
                return ResourceManager.GetString("ModuleObjectInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module object &quot;{1}&quot; ({0}) in {2} was removed..
        /// </summary>
        public static string ModuleObjectRemoved {
            get {
                return ResourceManager.GetString("ModuleObjectRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputFlow &quot;{0}&quot; finished to perform..
        /// </summary>
        public static string OutputFlowPerformed {
            get {
                return ResourceManager.GetString("OutputFlowPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputFlow &quot;{0}&quot; started to perform.
        ///  Selector: {1}
        ///  Input: {2}
        ///  Storage: {3}
        ///  Arguments:
        ///{4}
        ///  Output type: {5}.
        /// </summary>
        public static string OutputFlowPerforming {
            get {
                return ResourceManager.GetString("OutputFlowPerforming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servant &quot;{0}&quot; was aborted..
        /// </summary>
        public static string ServantAborted {
            get {
                return ResourceManager.GetString("ServantAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servant &quot;{0}&quot; is aborting..
        /// </summary>
        public static string ServantAborting {
            get {
                return ResourceManager.GetString("ServantAborting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servant &quot;{0}&quot; was started..
        /// </summary>
        public static string ServantStarted {
            get {
                return ResourceManager.GetString("ServantStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servant &quot;{0}&quot; is starting..
        /// </summary>
        public static string ServantStarting {
            get {
                return ResourceManager.GetString("ServantStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servant &quot;{0}&quot; was stopped..
        /// </summary>
        public static string ServantStopped {
            get {
                return ResourceManager.GetString("ServantStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servant &quot;{0}&quot; is stopping..
        /// </summary>
        public static string ServantStopping {
            get {
                return ResourceManager.GetString("ServantStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTweet Server was aborted..
        /// </summary>
        public static string ServerAborted {
            get {
                return ResourceManager.GetString("ServerAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTweet Server is aborting..
        /// </summary>
        public static string ServerAborting {
            get {
                return ResourceManager.GetString("ServerAborting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTweet Server was terminated..
        /// </summary>
        public static string ServerDisposed {
            get {
                return ResourceManager.GetString("ServerDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTweet Server is terminating..
        /// </summary>
        public static string ServerDisposing {
            get {
                return ResourceManager.GetString("ServerDisposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTweet Server was initialized..
        /// </summary>
        public static string ServerInitialized {
            get {
                return ResourceManager.GetString("ServerInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///MetaTweet Server version {1} on {2} ({3}) is initializing.
        ///Copyright © 2008-2010 Takeshi KIRIYA (aka takeshik) &lt;takeshik@users.sf.net&gt;, All rights reserved.
        ///This program comes with ABSOLUTELY NO WARRANTY and this is free software, and you are welcome to
        ///redistribute it under certain conditions; access &lt;http://www.metatweet.org/copying.html&gt; for details..
        /// </summary>
        public static string ServerInitializing {
            get {
                return ResourceManager.GetString("ServerInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTweet Server was paused..
        /// </summary>
        public static string ServerPaused {
            get {
                return ResourceManager.GetString("ServerPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTweet Server is pausing..
        /// </summary>
        public static string ServerPausing {
            get {
                return ResourceManager.GetString("ServerPausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTweet Server finished to execute request &quot;{0}&quot; (elapsed: {1})..
        /// </summary>
        public static string ServerRequestExecuted {
            get {
                return ResourceManager.GetString("ServerRequestExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTweet Server is executing request &quot;{0}&quot;..
        /// </summary>
        public static string ServerRequestExecuting {
            get {
                return ResourceManager.GetString("ServerRequestExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTweet Server failed to execute request &quot;{0}&quot; (elapsed: {1})..
        /// </summary>
        public static string ServerRequestFailed {
            get {
                return ResourceManager.GetString("ServerRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTweet Server was resumed..
        /// </summary>
        public static string ServerResumed {
            get {
                return ResourceManager.GetString("ServerResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTweet Server is resuming..
        /// </summary>
        public static string ServerResuming {
            get {
                return ResourceManager.GetString("ServerResuming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTweet Server would be exited not cleanly last time..
        /// </summary>
        public static string ServerRuntimeFileRemains {
            get {
                return ResourceManager.GetString("ServerRuntimeFileRemains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTweet Server was started..
        /// </summary>
        public static string ServerStarted {
            get {
                return ResourceManager.GetString("ServerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTweet Server is starting..
        /// </summary>
        public static string ServerStarting {
            get {
                return ResourceManager.GetString("ServerStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTweet Server was stopped..
        /// </summary>
        public static string ServerStopped {
            get {
                return ResourceManager.GetString("ServerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTweet Server is stopping..
        /// </summary>
        public static string ServerStopping {
            get {
                return ResourceManager.GetString("ServerStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; added new Account:
        ///  {1}.
        /// </summary>
        public static string StorageAddedAccount {
            get {
                return ResourceManager.GetString("StorageAddedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; added new Activity:
        ///  {1}.
        /// </summary>
        public static string StorageAddedActivity {
            get {
                return ResourceManager.GetString("StorageAddedActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; added new Annotation:
        ///  {1}.
        /// </summary>
        public static string StorageAddedAnnotation {
            get {
                return ResourceManager.GetString("StorageAddedAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; added new Account (existing):
        ///  {1}.
        /// </summary>
        public static string StorageAddedExistingAccount {
            get {
                return ResourceManager.GetString("StorageAddedExistingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; added new Activity (existing):
        ///  {1}.
        /// </summary>
        public static string StorageAddedExistingActivity {
            get {
                return ResourceManager.GetString("StorageAddedExistingActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; added new Annotation (existing):
        ///  {1}.
        /// </summary>
        public static string StorageAddedExistingAnnotation {
            get {
                return ResourceManager.GetString("StorageAddedExistingAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; added new Mark (existing):
        ///  {1}.
        /// </summary>
        public static string StorageAddedExistingMark {
            get {
                return ResourceManager.GetString("StorageAddedExistingMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; added new Reference (existing):
        ///  {1}.
        /// </summary>
        public static string StorageAddedExistingReference {
            get {
                return ResourceManager.GetString("StorageAddedExistingReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; added new Relation (existing):
        ///  {1}.
        /// </summary>
        public static string StorageAddedExistingRelation {
            get {
                return ResourceManager.GetString("StorageAddedExistingRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; added new Tag (existing):
        ///  {1}.
        /// </summary>
        public static string StorageAddedExistingTag {
            get {
                return ResourceManager.GetString("StorageAddedExistingTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; added new Mark:
        ///  {1}.
        /// </summary>
        public static string StorageAddedMark {
            get {
                return ResourceManager.GetString("StorageAddedMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; added new Reference:
        ///  {1}.
        /// </summary>
        public static string StorageAddedReference {
            get {
                return ResourceManager.GetString("StorageAddedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; added new Relation:
        ///  {1}.
        /// </summary>
        public static string StorageAddedRelation {
            get {
                return ResourceManager.GetString("StorageAddedRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; added new Tag:
        ///  {1}.
        /// </summary>
        public static string StorageAddedTag {
            get {
                return ResourceManager.GetString("StorageAddedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; finished querying Accounts (Query:
        ///{1}
        ///); returned {2}..
        /// </summary>
        public static string StorageGotAccounts {
            get {
                return ResourceManager.GetString("StorageGotAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; finished querying Activities (Query:
        ///{1}
        ///); returned {2}..
        /// </summary>
        public static string StorageGotActivities {
            get {
                return ResourceManager.GetString("StorageGotActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; finished querying Annotations (Query:
        ///{1}
        ///); returned {2}..
        /// </summary>
        public static string StorageGotAnnotations {
            get {
                return ResourceManager.GetString("StorageGotAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; finished querying Marks (Query:
        ///{1}
        ///); returned {2}..
        /// </summary>
        public static string StorageGotMarks {
            get {
                return ResourceManager.GetString("StorageGotMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; finished querying References (Query:
        ///{1}
        ///); returned {2}..
        /// </summary>
        public static string StorageGotReferences {
            get {
                return ResourceManager.GetString("StorageGotReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; finished querying Relations (Query:
        ///{1}
        ///); returned {2}..
        /// </summary>
        public static string StorageGotRelations {
            get {
                return ResourceManager.GetString("StorageGotRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; finished querying Tags (Query:
        ///{1}
        ///); returned {2}..
        /// </summary>
        public static string StorageGotTags {
            get {
                return ResourceManager.GetString("StorageGotTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &quot;{0}&quot; updated {1}..
        /// </summary>
        public static string StorageUpdated {
            get {
                return ResourceManager.GetString("StorageUpdated", resourceCulture);
            }
        }
    }
}
