//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3053
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSpect.MetaTweet.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XSpect.MetaTweet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Executed external code in &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CodeExecuted {
            get {
                return ResourceManager.GetString("CodeExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MetaTweet Server was initialized. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerInitialized {
            get {
                return ResourceManager.GetString("ServerInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MetaTweet Server version {0} on {1} ({2}) is initializing.\nCopyright © 2008-2009 Takeshi KIRIYA, XSpect Project &lt;takeshik@xspect.org&gt; All rights reserved.\nThis program comes with ABSOLUTELY NO WARRANTY and this is free software, and you are welcome to redistribute it under certain conditions; access &lt;http://metatweet.sf.net/license&gt; for details. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerInitializing {
            get {
                return ResourceManager.GetString("ServerInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MetaTweet Server was paused. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerPaused {
            get {
                return ResourceManager.GetString("ServerPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MetaTweet Server is pausing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerPausing {
            get {
                return ResourceManager.GetString("ServerPausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MetaTweet Server was resumed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerResumed {
            get {
                return ResourceManager.GetString("ServerResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MetaTweet Server is resuming. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerResuming {
            get {
                return ResourceManager.GetString("ServerResuming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MetaTweet Server was started. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerStarted {
            get {
                return ResourceManager.GetString("ServerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MetaTweet Server is starting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerStarting {
            get {
                return ResourceManager.GetString("ServerStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MetaTweet Server was stopped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerStopped {
            get {
                return ResourceManager.GetString("ServerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MetaTweet Server is stopping. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerStopping {
            get {
                return ResourceManager.GetString("ServerStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MetaTweet is terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerTerminated {
            get {
                return ResourceManager.GetString("ServerTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MetaTweet is terminating. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerTerminating {
            get {
                return ResourceManager.GetString("ServerTerminating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All subsystems in MetaTweet Server was ended. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerWaitedToEnd {
            get {
                return ResourceManager.GetString("ServerWaitedToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MetaTweet Server is waiting to end all subsystems. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerWaitingToEnd {
            get {
                return ResourceManager.GetString("ServerWaitingToEnd", resourceCulture);
            }
        }
    }
}
